[2024-07-30T11:55:20.779+0000] {processor.py:161} INFO - Started process (PID=4742) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T11:55:20.780+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T11:55:20.781+0000] {logging_mixin.py:188} INFO - [2024-07-30T11:55:20.781+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T11:55:20.785+0000] {logging_mixin.py:188} INFO - [2024-07-30T11:55:20.784+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T11:55:20.785+0000] {logging_mixin.py:188} INFO - [2024-07-30T11:55:20.785+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T11:55:20.785+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T11:55:20.798+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T11:56:13.349+0000] {processor.py:161} INFO - Started process (PID=4793) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T11:56:13.350+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T11:56:13.352+0000] {logging_mixin.py:188} INFO - [2024-07-30T11:56:13.351+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T11:56:13.355+0000] {logging_mixin.py:188} INFO - [2024-07-30T11:56:13.354+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T11:56:13.355+0000] {logging_mixin.py:188} INFO - [2024-07-30T11:56:13.355+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T11:56:13.356+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T11:56:13.366+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-07-30T11:57:01.476+0000] {processor.py:161} INFO - Started process (PID=4844) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T11:57:01.478+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T11:57:01.480+0000] {logging_mixin.py:188} INFO - [2024-07-30T11:57:01.479+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T11:57:01.483+0000] {logging_mixin.py:188} INFO - [2024-07-30T11:57:01.482+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T11:57:01.483+0000] {logging_mixin.py:188} INFO - [2024-07-30T11:57:01.483+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T11:57:01.484+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T11:57:01.494+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-07-30T11:57:59.268+0000] {processor.py:161} INFO - Started process (PID=4903) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T11:57:59.269+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T11:57:59.271+0000] {logging_mixin.py:188} INFO - [2024-07-30T11:57:59.271+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T11:57:59.274+0000] {logging_mixin.py:188} INFO - [2024-07-30T11:57:59.274+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T11:57:59.275+0000] {logging_mixin.py:188} INFO - [2024-07-30T11:57:59.275+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T11:57:59.275+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T11:57:59.286+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-07-30T11:58:57.905+0000] {processor.py:161} INFO - Started process (PID=4965) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T11:58:57.906+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T11:58:57.908+0000] {logging_mixin.py:188} INFO - [2024-07-30T11:58:57.907+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T11:58:57.911+0000] {logging_mixin.py:188} INFO - [2024-07-30T11:58:57.910+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T11:58:57.911+0000] {logging_mixin.py:188} INFO - [2024-07-30T11:58:57.911+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T11:58:57.912+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T11:58:57.922+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-07-30T11:59:55.313+0000] {processor.py:161} INFO - Started process (PID=5026) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T11:59:55.315+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T11:59:55.316+0000] {logging_mixin.py:188} INFO - [2024-07-30T11:59:55.316+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T11:59:55.320+0000] {logging_mixin.py:188} INFO - [2024-07-30T11:59:55.319+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T11:59:55.320+0000] {logging_mixin.py:188} INFO - [2024-07-30T11:59:55.320+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T11:59:55.320+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T11:59:55.331+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-07-30T12:00:57.277+0000] {processor.py:161} INFO - Started process (PID=5093) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:00:57.278+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:00:57.281+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:00:57.280+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:00:57.284+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:00:57.283+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:00:57.285+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:00:57.284+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:00:57.285+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:00:57.295+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T12:01:57.662+0000] {processor.py:161} INFO - Started process (PID=5154) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:01:57.663+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:01:57.665+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:01:57.665+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:01:57.669+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:01:57.668+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:01:57.669+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:01:57.669+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:01:57.669+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:01:57.681+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T12:02:58.909+0000] {processor.py:161} INFO - Started process (PID=5217) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:02:58.910+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:02:58.913+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:02:58.912+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:02:58.916+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:02:58.916+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:02:58.917+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:02:58.916+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:02:58.917+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:02:58.927+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T12:03:59.791+0000] {processor.py:161} INFO - Started process (PID=5294) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:03:59.793+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:03:59.794+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:03:59.794+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:03:59.798+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:03:59.797+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:03:59.798+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:03:59.798+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:03:59.798+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:03:59.810+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-07-30T12:04:46.332+0000] {processor.py:161} INFO - Started process (PID=5344) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:04:46.334+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:04:46.336+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:04:46.335+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:04:46.339+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:04:46.338+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:04:46.340+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:04:46.339+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:04:46.340+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:04:46.351+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T12:05:46.612+0000] {processor.py:161} INFO - Started process (PID=5413) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:05:46.614+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:05:46.615+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:05:46.615+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:05:46.619+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:05:46.618+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:05:46.619+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:05:46.619+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:05:46.619+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:05:46.630+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-07-30T12:06:46.779+0000] {processor.py:161} INFO - Started process (PID=5475) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:06:46.781+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:06:46.783+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:06:46.782+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:06:46.786+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:06:46.785+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:06:46.786+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:06:46.786+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:06:46.786+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:06:46.797+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-07-30T12:07:48.602+0000] {processor.py:161} INFO - Started process (PID=5540) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:07:48.604+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:07:48.606+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:07:48.605+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:07:48.609+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:07:48.608+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:07:48.609+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:07:48.609+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:07:48.610+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:07:48.620+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-07-30T12:08:47.990+0000] {processor.py:161} INFO - Started process (PID=5604) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:08:47.992+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:08:47.993+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:08:47.993+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:08:47.997+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:08:47.996+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:08:47.997+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:08:47.997+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:08:47.998+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:08:48.009+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T12:09:49.692+0000] {processor.py:161} INFO - Started process (PID=5669) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:09:49.694+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:09:49.696+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:09:49.695+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:09:49.699+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:09:49.698+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:09:49.699+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:09:49.699+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:09:49.700+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:09:49.710+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-07-30T12:10:50.233+0000] {processor.py:161} INFO - Started process (PID=5737) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:10:50.235+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:10:50.236+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:10:50.236+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:10:50.240+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:10:50.239+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:10:50.240+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:10:50.240+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:10:50.240+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:10:50.251+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T12:11:50.476+0000] {processor.py:161} INFO - Started process (PID=5798) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:11:50.478+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:11:50.479+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:11:50.479+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:11:50.483+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:11:50.482+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:11:50.483+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:11:50.483+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:11:50.483+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:11:50.494+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-07-30T12:12:49.917+0000] {processor.py:161} INFO - Started process (PID=5860) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:12:49.918+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:12:49.920+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:12:49.919+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:12:49.923+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:12:49.922+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:12:49.923+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:12:49.923+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:12:49.924+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:12:49.934+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-07-30T12:13:51.969+0000] {processor.py:161} INFO - Started process (PID=5923) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:13:51.970+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:13:51.972+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:13:51.972+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:13:51.976+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:13:51.975+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:13:51.976+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:13:51.976+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:13:51.977+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:13:51.988+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T12:14:54.267+0000] {processor.py:161} INFO - Started process (PID=5987) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:14:54.268+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:14:54.270+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:14:54.269+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:14:54.273+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:14:54.272+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:14:54.273+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:14:54.273+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:14:54.274+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:14:54.284+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-07-30T12:15:54.297+0000] {processor.py:161} INFO - Started process (PID=6054) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:15:54.298+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:15:54.300+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:15:54.300+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:15:54.304+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:15:54.303+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:15:54.304+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:15:54.304+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:15:54.304+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:15:54.315+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-07-30T12:16:56.439+0000] {processor.py:161} INFO - Started process (PID=6117) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:16:56.440+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:16:56.442+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:16:56.442+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:16:56.446+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:16:56.445+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:16:56.446+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:16:56.446+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:16:56.446+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:16:56.457+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-07-30T12:17:58.754+0000] {processor.py:161} INFO - Started process (PID=6182) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:17:58.756+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:17:58.757+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:17:58.757+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:17:58.761+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:17:58.760+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:17:58.761+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:17:58.761+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:17:58.761+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:17:58.772+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-07-30T12:19:04.740+0000] {processor.py:161} INFO - Started process (PID=6256) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:19:04.742+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:19:04.744+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:19:04.743+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:19:04.747+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:19:04.746+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:19:04.748+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:19:04.747+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:19:04.748+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:19:04.759+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T12:20:10.235+0000] {processor.py:161} INFO - Started process (PID=6331) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:20:10.237+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:20:10.239+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:20:10.238+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:20:10.242+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:20:10.242+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:20:10.243+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:20:10.243+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:20:10.243+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:20:10.255+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-07-30T12:21:04.061+0000] {processor.py:161} INFO - Started process (PID=6389) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:21:04.063+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:21:04.064+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:21:04.064+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:21:04.068+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:21:04.067+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:21:04.068+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:21:04.068+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:21:04.069+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:21:04.080+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-07-30T12:22:02.506+0000] {processor.py:161} INFO - Started process (PID=6450) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:22:02.508+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:22:02.509+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:22:02.509+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:22:02.513+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:22:02.512+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:22:02.513+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:22:02.513+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:22:02.513+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:22:02.525+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-07-30T12:23:02.853+0000] {processor.py:161} INFO - Started process (PID=6511) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:23:02.855+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:23:02.857+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:23:02.856+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:23:02.860+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:23:02.859+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:23:02.861+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:23:02.860+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:23:02.861+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:23:02.873+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-07-30T12:24:05.183+0000] {processor.py:161} INFO - Started process (PID=6576) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:24:05.185+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:24:05.186+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:24:05.186+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:24:05.190+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:24:05.189+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:24:05.190+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:24:05.190+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:24:05.191+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:24:05.202+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-07-30T12:25:00.598+0000] {processor.py:161} INFO - Started process (PID=6635) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:25:00.600+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:25:00.601+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:25:00.601+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:25:00.605+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:25:00.604+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:25:00.605+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:25:00.605+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:25:00.606+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:25:00.617+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-07-30T12:25:58.326+0000] {processor.py:161} INFO - Started process (PID=6703) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:25:58.327+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:25:58.329+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:25:58.328+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:25:58.332+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:25:58.331+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:25:58.333+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:25:58.332+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:25:58.333+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:25:58.344+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T12:26:55.981+0000] {processor.py:161} INFO - Started process (PID=6766) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:26:55.983+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:26:55.985+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:26:55.984+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:26:55.988+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:26:55.987+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:26:55.988+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:26:55.988+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:26:55.989+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:26:56.000+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T12:27:58.899+0000] {processor.py:161} INFO - Started process (PID=6829) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:27:58.901+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:27:58.902+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:27:58.902+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:27:58.906+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:27:58.905+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:27:58.906+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:27:58.906+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:27:58.906+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:27:58.917+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T12:29:03.479+0000] {processor.py:161} INFO - Started process (PID=6894) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:29:03.481+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:29:03.483+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:29:03.482+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:29:03.486+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:29:03.485+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:29:03.486+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:29:03.486+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:29:03.487+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:29:03.498+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T12:30:02.226+0000] {processor.py:161} INFO - Started process (PID=6958) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:30:02.228+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:30:02.230+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:30:02.229+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:30:02.233+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:30:02.233+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:30:02.234+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:30:02.234+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:30:02.234+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:30:02.245+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-07-30T12:31:02.020+0000] {processor.py:161} INFO - Started process (PID=7022) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:31:02.021+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:31:02.023+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:31:02.023+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:31:02.027+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:31:02.026+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:31:02.027+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:31:02.027+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:31:02.028+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:31:02.039+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T12:32:00.569+0000] {processor.py:161} INFO - Started process (PID=7082) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:32:00.571+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:32:00.573+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:32:00.572+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:32:00.576+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:32:00.575+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:32:00.577+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:32:00.576+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:32:00.577+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:32:00.587+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-07-30T12:33:03.779+0000] {processor.py:161} INFO - Started process (PID=7147) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:33:03.780+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:33:03.782+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:33:03.782+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:33:03.786+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:33:03.785+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:33:03.786+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:33:03.786+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:33:03.786+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:33:03.797+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T12:34:01.748+0000] {processor.py:161} INFO - Started process (PID=7208) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:34:01.749+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:34:01.751+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:34:01.750+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:34:01.754+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:34:01.754+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:34:01.755+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:34:01.755+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:34:01.755+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:34:01.766+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T12:34:59.382+0000] {processor.py:161} INFO - Started process (PID=7269) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:34:59.384+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:34:59.386+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:34:59.385+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:34:59.389+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:34:59.388+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:34:59.389+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:34:59.389+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:34:59.390+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:34:59.401+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-07-30T12:35:59.915+0000] {processor.py:161} INFO - Started process (PID=7334) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:35:59.916+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:35:59.918+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:35:59.917+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:35:59.921+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:35:59.920+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:35:59.922+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:35:59.921+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:35:59.922+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:35:59.933+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T12:37:04.161+0000] {processor.py:161} INFO - Started process (PID=7399) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:37:04.162+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:37:04.164+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:37:04.164+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:37:04.168+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:37:04.167+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:37:04.168+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:37:04.168+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:37:04.168+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:37:04.180+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T12:38:01.843+0000] {processor.py:161} INFO - Started process (PID=7461) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:38:01.845+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:38:01.846+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:38:01.846+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:38:01.850+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:38:01.849+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:38:01.850+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:38:01.850+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:38:01.851+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:38:01.862+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-07-30T12:38:58.982+0000] {processor.py:161} INFO - Started process (PID=7521) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:38:58.984+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:38:58.986+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:38:58.985+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:38:58.989+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:38:58.988+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:38:58.989+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:38:58.989+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:38:58.990+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:38:59.000+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-07-30T12:39:56.834+0000] {processor.py:161} INFO - Started process (PID=7582) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:39:56.836+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:39:56.837+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:39:56.837+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:39:56.841+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:39:56.840+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:39:56.841+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:39:56.841+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:39:56.842+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:39:56.853+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T12:40:55.544+0000] {processor.py:161} INFO - Started process (PID=7647) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:40:55.545+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:40:55.547+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:40:55.547+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:40:55.551+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:40:55.550+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:40:55.551+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:40:55.551+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:40:55.551+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:40:55.562+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-07-30T12:41:55.274+0000] {processor.py:161} INFO - Started process (PID=7712) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:41:55.275+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:41:55.277+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:41:55.276+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:41:55.280+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:41:55.279+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:41:55.281+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:41:55.280+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:41:55.281+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:41:55.292+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-07-30T12:42:57.120+0000] {processor.py:161} INFO - Started process (PID=7776) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:42:57.122+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:42:57.123+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:42:57.123+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:42:57.127+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:42:57.126+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:42:57.127+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:42:57.127+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:42:57.127+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:42:57.138+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T12:43:58.579+0000] {processor.py:161} INFO - Started process (PID=7838) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:43:58.580+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:43:58.582+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:43:58.581+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:43:58.585+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:43:58.584+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:43:58.585+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:43:58.585+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:43:58.586+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:43:58.597+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-07-30T12:44:59.245+0000] {processor.py:161} INFO - Started process (PID=7900) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:44:59.247+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:44:59.249+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:44:59.248+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:44:59.252+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:44:59.251+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:44:59.253+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:44:59.253+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:44:59.253+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:44:59.264+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-07-30T12:45:57.529+0000] {processor.py:161} INFO - Started process (PID=7968) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:45:57.531+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:45:57.532+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:45:57.532+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:45:57.536+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:45:57.535+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:45:57.536+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:45:57.536+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:45:57.537+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:45:57.548+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T12:46:55.455+0000] {processor.py:161} INFO - Started process (PID=8029) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:46:55.457+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:46:55.458+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:46:55.458+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:46:55.462+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:46:55.461+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:46:55.462+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:46:55.462+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:46:55.462+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:46:55.473+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-07-30T12:47:54.636+0000] {processor.py:161} INFO - Started process (PID=8090) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:47:54.637+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:47:54.639+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:47:54.639+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:47:54.642+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:47:54.642+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:47:54.643+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:47:54.643+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:47:54.643+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:47:54.654+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T12:48:51.560+0000] {processor.py:161} INFO - Started process (PID=8150) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:48:51.562+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:48:51.564+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:48:51.563+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:48:51.567+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:48:51.567+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:48:51.568+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:48:51.568+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:48:51.568+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:48:51.579+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T12:49:52.035+0000] {processor.py:161} INFO - Started process (PID=8212) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:49:52.037+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:49:52.039+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:49:52.038+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:49:52.042+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:49:52.041+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:49:52.042+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:49:52.042+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:49:52.043+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:49:52.054+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T12:50:48.742+0000] {processor.py:161} INFO - Started process (PID=8276) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:50:48.743+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:50:48.745+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:50:48.745+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:50:48.749+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:50:48.748+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:50:48.749+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:50:48.749+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:50:48.749+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:50:48.760+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T12:51:49.699+0000] {processor.py:161} INFO - Started process (PID=8338) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:51:49.700+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:51:49.702+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:51:49.701+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:51:49.705+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:51:49.704+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:51:49.706+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:51:49.705+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:51:49.706+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:51:49.717+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T12:52:52.831+0000] {processor.py:161} INFO - Started process (PID=8402) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:52:52.833+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:52:52.834+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:52:52.834+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:52:52.838+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:52:52.837+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:52:52.838+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:52:52.838+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:52:52.838+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:52:52.849+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T12:53:56.737+0000] {processor.py:161} INFO - Started process (PID=8730) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:53:56.738+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:53:56.740+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:53:56.740+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:53:56.744+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:53:56.743+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:53:56.744+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:53:56.744+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:53:56.744+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:53:56.755+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T12:54:53.384+0000] {processor.py:161} INFO - Started process (PID=8789) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:54:53.386+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:54:53.388+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:54:53.387+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:54:53.391+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:54:53.390+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:54:53.392+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:54:53.391+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:54:53.392+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:54:53.403+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T12:55:50.280+0000] {processor.py:161} INFO - Started process (PID=9018) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:55:50.282+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:55:50.284+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:55:50.283+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:55:50.287+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:55:50.287+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:55:50.288+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:55:50.288+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:55:50.288+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:55:50.299+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T12:56:50.429+0000] {processor.py:161} INFO - Started process (PID=9081) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:56:50.430+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:56:50.432+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:56:50.431+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:56:50.435+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:56:50.435+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:56:50.436+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:56:50.436+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:56:50.436+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:56:50.447+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T12:57:50.567+0000] {processor.py:161} INFO - Started process (PID=9144) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:57:50.569+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:57:50.571+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:57:50.570+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:57:50.574+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:57:50.573+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:57:50.574+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:57:50.574+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:57:50.575+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:57:50.585+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-07-30T12:58:49.172+0000] {processor.py:161} INFO - Started process (PID=9207) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:58:49.173+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:58:49.175+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:58:49.174+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:58:49.178+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:58:49.177+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:58:49.178+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:58:49.178+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:58:49.179+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:58:49.190+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-07-30T12:59:41.827+0000] {processor.py:161} INFO - Started process (PID=9263) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:59:41.828+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T12:59:41.830+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:59:41.829+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:59:41.833+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:59:41.833+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T12:59:41.834+0000] {logging_mixin.py:188} INFO - [2024-07-30T12:59:41.834+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T12:59:41.834+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T12:59:41.845+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T13:00:46.994+0000] {processor.py:161} INFO - Started process (PID=9330) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T13:00:46.995+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T13:00:46.997+0000] {logging_mixin.py:188} INFO - [2024-07-30T13:00:46.997+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T13:00:47.000+0000] {logging_mixin.py:188} INFO - [2024-07-30T13:00:47.000+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T13:00:47.001+0000] {logging_mixin.py:188} INFO - [2024-07-30T13:00:47.001+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T13:00:47.001+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T13:00:47.012+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T13:01:48.956+0000] {processor.py:161} INFO - Started process (PID=9395) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T13:01:48.958+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T13:01:48.959+0000] {logging_mixin.py:188} INFO - [2024-07-30T13:01:48.959+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T13:01:48.963+0000] {logging_mixin.py:188} INFO - [2024-07-30T13:01:48.962+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T13:01:48.963+0000] {logging_mixin.py:188} INFO - [2024-07-30T13:01:48.963+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T13:01:48.964+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T13:01:48.974+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T13:02:45.994+0000] {processor.py:161} INFO - Started process (PID=9455) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T13:02:45.996+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T13:02:45.998+0000] {logging_mixin.py:188} INFO - [2024-07-30T13:02:45.997+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T13:02:46.001+0000] {logging_mixin.py:188} INFO - [2024-07-30T13:02:46.000+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T13:02:46.001+0000] {logging_mixin.py:188} INFO - [2024-07-30T13:02:46.001+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T13:02:46.002+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T13:02:46.012+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T13:03:43.958+0000] {processor.py:161} INFO - Started process (PID=9515) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T13:03:43.959+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T13:03:43.961+0000] {logging_mixin.py:188} INFO - [2024-07-30T13:03:43.961+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T13:03:43.965+0000] {logging_mixin.py:188} INFO - [2024-07-30T13:03:43.964+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T13:03:43.965+0000] {logging_mixin.py:188} INFO - [2024-07-30T13:03:43.965+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T13:03:43.965+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T13:03:43.977+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T13:04:46.132+0000] {processor.py:161} INFO - Started process (PID=9580) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T13:04:46.134+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T13:04:46.136+0000] {logging_mixin.py:188} INFO - [2024-07-30T13:04:46.135+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T13:04:46.139+0000] {logging_mixin.py:188} INFO - [2024-07-30T13:04:46.138+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T13:04:46.139+0000] {logging_mixin.py:188} INFO - [2024-07-30T13:04:46.139+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T13:04:46.140+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T13:04:46.151+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T13:05:48.337+0000] {processor.py:161} INFO - Started process (PID=9647) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T13:05:48.338+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T13:05:48.340+0000] {logging_mixin.py:188} INFO - [2024-07-30T13:05:48.340+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T13:05:48.343+0000] {logging_mixin.py:188} INFO - [2024-07-30T13:05:48.343+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T13:05:48.344+0000] {logging_mixin.py:188} INFO - [2024-07-30T13:05:48.344+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T13:05:48.344+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T13:05:48.355+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T13:06:43.727+0000] {processor.py:161} INFO - Started process (PID=9708) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T13:06:43.728+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T13:06:43.730+0000] {logging_mixin.py:188} INFO - [2024-07-30T13:06:43.730+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T13:06:43.733+0000] {logging_mixin.py:188} INFO - [2024-07-30T13:06:43.733+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T13:06:43.734+0000] {logging_mixin.py:188} INFO - [2024-07-30T13:06:43.734+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T13:06:43.734+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T13:06:43.745+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T13:07:42.525+0000] {processor.py:161} INFO - Started process (PID=9770) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T13:07:42.527+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T13:07:42.529+0000] {logging_mixin.py:188} INFO - [2024-07-30T13:07:42.528+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T13:07:42.532+0000] {logging_mixin.py:188} INFO - [2024-07-30T13:07:42.532+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T13:07:42.533+0000] {logging_mixin.py:188} INFO - [2024-07-30T13:07:42.533+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T13:07:42.533+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T13:07:42.544+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-07-30T13:08:42.453+0000] {processor.py:161} INFO - Started process (PID=9831) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T13:08:42.455+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T13:08:42.457+0000] {logging_mixin.py:188} INFO - [2024-07-30T13:08:42.456+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T13:08:42.460+0000] {logging_mixin.py:188} INFO - [2024-07-30T13:08:42.460+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T13:08:42.461+0000] {logging_mixin.py:188} INFO - [2024-07-30T13:08:42.461+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T13:08:42.461+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T13:08:42.472+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-07-30T13:09:43.253+0000] {processor.py:161} INFO - Started process (PID=9893) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T13:09:43.255+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T13:09:43.256+0000] {logging_mixin.py:188} INFO - [2024-07-30T13:09:43.256+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T13:09:43.260+0000] {logging_mixin.py:188} INFO - [2024-07-30T13:09:43.259+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T13:09:43.260+0000] {logging_mixin.py:188} INFO - [2024-07-30T13:09:43.260+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T13:09:43.261+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T13:09:43.271+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-07-30T13:10:44.858+0000] {processor.py:161} INFO - Started process (PID=9962) to work on /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T13:10:44.859+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-07-30T13:10:44.861+0000] {logging_mixin.py:188} INFO - [2024-07-30T13:10:44.860+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T13:10:44.864+0000] {logging_mixin.py:188} INFO - [2024-07-30T13:10:44.864+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-07-30T13:10:44.865+0000] {logging_mixin.py:188} INFO - [2024-07-30T13:10:44.865+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-07-30T13:10:44.865+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-07-30T13:10:44.876+0000] {processor.py:183} INFO - Processing /home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
